---

- hosts: all
  become: true
  tasks:

#  - name: update repo index
#    apt:
#      update_cache: yes
#    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache2 and php package for U
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
