---

- hosts: all
  become: true
  pre_tasks:

#  - name: install updates (Ubuntu)
#    apt:
#      upgrade: dist
#      update_cache: yes
#    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php package for U
    tags: apache
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: start apache
    tags: apache
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

  - name: change email
    tags: apache
    lineinfile:
      path: /etc/apache2/sites-available/000-default.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin test@testing.com
    when: ansible_distribution == "Ubuntu"
    register: apache2

  - name: restart apache
    tags: apache
    service:
      name: apache2
      state: restarted
    when: apache2.changed

  - name: copy default html file
    tags: apache
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: install unzip
    package:
      name: unzip

#  - name: install terraform
#    unarchive:
#      src: https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip
#      dest: /usr/local/bin
#      remote_src: yes
#      mode: 0755
#      owner: root
#      group: root
